server:
  port: 9090
spring:
  application:
    name: MilitiaAdmin
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/militia—admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 314914.fgz
#       session 失效时间（分钟）
  session:
      timeout: 86400
      store-type: redis
#    redis 配置
  redis:
    port: 6379
    host: 192.168.208.130
    database: 4
    password: 314914.fgz
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
jwt:
  secret-key: "militia-admin-user"
  expiration-time: 86400000  # 24小时，单位毫秒

logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

